

services:

  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    ports:
      - "9080:8080"
